// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: api/v1/EventService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventServiceV1_GetEvent_FullMethodName          = "/event.EventServiceV1/GetEvent"
	EventServiceV1_CreateEvent_FullMethodName       = "/event.EventServiceV1/CreateEvent"
	EventServiceV1_UpdateEvent_FullMethodName       = "/event.EventServiceV1/UpdateEvent"
	EventServiceV1_DeleteEvent_FullMethodName       = "/event.EventServiceV1/DeleteEvent"
	EventServiceV1_GetEventsByPeriod_FullMethodName = "/event.EventServiceV1/GetEventsByPeriod"
)

// EventServiceV1Client is the client API for EventServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceV1Client interface {
	GetEvent(ctx context.Context, in *EventIDRequest, opts ...grpc.CallOption) (*EventResponse, error)
	CreateEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	UpdateEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	DeleteEvent(ctx context.Context, in *EventIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetEventsByPeriod(ctx context.Context, in *TimePeriodRequest, opts ...grpc.CallOption) (*EventsResponse, error)
}

type eventServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceV1Client(cc grpc.ClientConnInterface) EventServiceV1Client {
	return &eventServiceV1Client{cc}
}

func (c *eventServiceV1Client) GetEvent(ctx context.Context, in *EventIDRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventServiceV1_GetEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceV1Client) CreateEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventServiceV1_CreateEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceV1Client) UpdateEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventServiceV1_UpdateEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceV1Client) DeleteEvent(ctx context.Context, in *EventIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventServiceV1_DeleteEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceV1Client) GetEventsByPeriod(ctx context.Context, in *TimePeriodRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, EventServiceV1_GetEventsByPeriod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceV1Server is the server API for EventServiceV1 service.
// All implementations must embed UnimplementedEventServiceV1Server
// for forward compatibility
type EventServiceV1Server interface {
	GetEvent(context.Context, *EventIDRequest) (*EventResponse, error)
	CreateEvent(context.Context, *EventRequest) (*EventResponse, error)
	UpdateEvent(context.Context, *EventRequest) (*EventResponse, error)
	DeleteEvent(context.Context, *EventIDRequest) (*emptypb.Empty, error)
	GetEventsByPeriod(context.Context, *TimePeriodRequest) (*EventsResponse, error)
	mustEmbedUnimplementedEventServiceV1Server()
}

// UnimplementedEventServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedEventServiceV1Server struct {
}

func (UnimplementedEventServiceV1Server) GetEvent(context.Context, *EventIDRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventServiceV1Server) CreateEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceV1Server) UpdateEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventServiceV1Server) DeleteEvent(context.Context, *EventIDRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventServiceV1Server) GetEventsByPeriod(context.Context, *TimePeriodRequest) (*EventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsByPeriod not implemented")
}
func (UnimplementedEventServiceV1Server) mustEmbedUnimplementedEventServiceV1Server() {}

// UnsafeEventServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceV1Server will
// result in compilation errors.
type UnsafeEventServiceV1Server interface {
	mustEmbedUnimplementedEventServiceV1Server()
}

func RegisterEventServiceV1Server(s grpc.ServiceRegistrar, srv EventServiceV1Server) {
	s.RegisterService(&EventServiceV1_ServiceDesc, srv)
}

func _EventServiceV1_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceV1Server).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventServiceV1_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceV1Server).GetEvent(ctx, req.(*EventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventServiceV1_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceV1Server).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventServiceV1_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceV1Server).CreateEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventServiceV1_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceV1Server).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventServiceV1_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceV1Server).UpdateEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventServiceV1_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceV1Server).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventServiceV1_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceV1Server).DeleteEvent(ctx, req.(*EventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventServiceV1_GetEventsByPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimePeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceV1Server).GetEventsByPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventServiceV1_GetEventsByPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceV1Server).GetEventsByPeriod(ctx, req.(*TimePeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventServiceV1_ServiceDesc is the grpc.ServiceDesc for EventServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventServiceV1",
	HandlerType: (*EventServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvent",
			Handler:    _EventServiceV1_GetEvent_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _EventServiceV1_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventServiceV1_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventServiceV1_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEventsByPeriod",
			Handler:    _EventServiceV1_GetEventsByPeriod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/EventService.proto",
}
