# Config file for calendar service
APP:
  HOST: '127.0.0.1'
  PORT: 8080
  GRPC_HOST: '127.0.0.1'
  GRPC_PORT: 50051
  GRPC_GW_HOST: '127.0.0.1'
  GRPC_GW_PORT: 3000
  DEBUG: true
  LOG_LEVEL: 'info'
  SHUTDOWN_TIMEOUT_SECOND: 30
  READ_TIMEOUT_SECOND: 10
  READ_HEADER_TIMEOUT_SECOND: 10
DB:
  USERNAME: 'admin'
  PASSWORD: 'password'
  DATABASE: 'calendar-service'
  HOST: '127.0.0.1'
  PORT: 5432
  SSL_MODE: 'disable'
RABBITMQ:
  HOST: '127.0.0.1'
  PORT: 5675
  USERNAME: 'admin'
  PASSWORD: 'password'
SCHEDULER:
  PUBLISH_PERIOD_TIME_SECOND: 10
  EVENT_LIFETIME_SECOND: 31536000

USE_CACHE_DB: false