// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RabbitClient is an autogenerated mock type for the RabbitClient type
type RabbitClient struct {
	mock.Mock
}

// Consume provides a mock function with given fields: name
func (_m *RabbitClient) Consume(name string) (<-chan []byte, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 <-chan []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (<-chan []byte, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) <-chan []byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publish provides a mock function with given fields: ctx, queueName, data
func (_m *RabbitClient) Publish(ctx context.Context, queueName string, data []byte) error {
	ret := _m.Called(ctx, queueName, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, queueName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRabbitClient creates a new instance of RabbitClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRabbitClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RabbitClient {
	mock := &RabbitClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
