// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeEventServiceV1Server is an autogenerated mock type for the UnsafeEventServiceV1Server type
type UnsafeEventServiceV1Server struct {
	mock.Mock
}

// mustEmbedUnimplementedEventServiceV1Server provides a mock function with given fields:
func (_m *UnsafeEventServiceV1Server) mustEmbedUnimplementedEventServiceV1Server() {
	_m.Called()
}

// NewUnsafeEventServiceV1Server creates a new instance of UnsafeEventServiceV1Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeEventServiceV1Server(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeEventServiceV1Server {
	mock := &UnsafeEventServiceV1Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
